name: Publish

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Build image
    runs-on: ubuntu-22.04
    if: github.repository == 'nextcloud/HaRP'
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: nextcloud-appapi-harp-buildx-${{ github.sha }}
          restore-keys: |
            nextcloud-appapi-harp-buildx-

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Build container image
        uses: docker/build-push-action@v5
        with:
          push: false
          context: .
          platforms: linux/amd64
          file: Dockerfile
          tags: nextcloud-appapi-harp:${{ github.sha }}
          load: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Publish container image
        uses: docker/build-push-action@v5
        if: github.ref == 'refs/heads/main' || github.event_name == 'release'
        with:
          push: true
          context: .
          platforms: linux/amd64,linux/arm64
          file: Dockerfile
          tags: |
            ghcr.io/nextcloud/nextcloud-appapi-harp:${{ github.event_name == 'release' && 'release' || 'latest' }}
            ghcr.io/nextcloud/nextcloud-appapi-harp:${{ github.ref_name }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Move cache
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
